jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Display Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests and generate coverage report
      run: mvn test jacoco:report
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.1.0
      with:
        args: >
          -Dsonar.projectKey=PROJECT_KEY
          -Dsonar.organization=ORGANIZATION
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build
